### ISSUE TITLE
`az-property-description` rule breaks on node js

### ISSUE THREAD

**Issue by jjwedemyer** [Azure/azure-api-style-guide#4]
Hi,
i'm encountering an error using this ruleset with the spectral cli executable, whilst everything is working in the VSCode extension.

in my node.js setup the program is exiting with `'undefined' is not defined` where i've tracked down to the `?(@.$ref === undefined)` expression on [L174](https://github.com/Azure/azure-api-style-guide/blob/main/spectral.yaml#L174)

In VSCode this rule seems to be running just fine, even showing all found issues with the OAS.

**Comment by mikekistler** [comment]
Thanks for the bug report.  I will investigate!

Can you let me know the version of Node you have installed, in case that's relevant.

And if you have a small API doc that recreates the problem that would be particularly helpful.

**Comment by mikekistler** [comment]
Ah ... I missed that you are using the spectral-cli executable in your original bug report.  I've uncovered [several issues with this new Spectral release](https://github.com/stoplightio/spectral/issues/created_by/mikekistler).  It's hard to know if the problem with `az-property-description` is one of them or not, but until the others are fixed my recommendation is to use the old `@stoplight/spectral@5.9.2` package.  I'm pretty sure the VSCode extension is still using this and that's why you don't see the failure there.

As an aside, I really dislike the JSON Path used for this rule and `az-property-names-convention`. But it is very hard to write a JSON Path yields all the schemas in the doc, since schemas can live in so many places.
